name: Download Torrent and Save as Artifact

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'لینک مگنت تورنت'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install aria2
        run: sudo apt-get update && sudo apt-get install -y aria2

      - name: Download with aria2
        run: |
          aria2c --seed-time=0 \
                 --max-connection-per-server=16 \
                 --split=16 \
                 --min-split-size=1M \
                 --console-log-level=notice \
                 "${{ inputs.torrent_url }}"

      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: torrent-download
          path: ./
